# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebook', '0004_auto_20170404_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
            preserve_default=False,
        ),
    ]
