# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebook', '0006_category_shortened'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
