# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebook', '0007_category_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='hello',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
