# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebook', '0008_language_hello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 15, 13, 17, 35, 959053, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
