# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebook', '0010_auto_20170415_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
