# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebook', '0011_auto_20170415_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
