# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebook', '0013_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='share_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
