# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-25 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasebook', '0014_category_share_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='share_url',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
